name: 'Setup Tools'
description: 'Setup tools needed in repo'

runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-s-builds-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-s-builds-${{ env.cache-name }}-
          ${{ runner.os }}-s-builds-
          ${{ runner.os }}-s-
    - name: Install dependencies
      shell: bash
      run: npm ci