name: E2E

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ios:    
    if: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          export PATH="$PATH":"$HOME/.maestro/bin"
          brew tap facebook/fb
          brew install facebook/fb/idb-companion
          ./e2e/scripts/RuniOSTest.sh
  android:    
    if: true
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Sdk
        run: |
           yes Y | sdkmanager --licenses
      - name: "Run Tests"
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          export PATH="$PATH":"$HOME/.maestro/bin"
          ./e2e/scripts/RunAndroidTest.sh