name: E2E

on:
  workflow_dispatch

jobs:
  ios:    
    if: true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm i
          npm run build
      - run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          export PATH="$PATH":"$HOME/.maestro/bin"
          brew tap facebook/fb
          brew install facebook/fb/idb-companion
          npm run run-e2e-ios

  android:    
    if: true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Add avdmanager and sdkmanager to system PATH
        run: |
            echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }}" >> $GITHUB_PATH
      - name: Sdk
        run: |
           yes Y | sdkmanager --licenses
      - run: |
          npm i
          npm run build
      - name: "Run Tests"
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          export PATH="$PATH":"$HOME/.maestro/bin"
          npm run run-e2e-android